#! /usr/bin/env python
from __future__ import division

import rospy
from geometry_msgs.msg import Quaternion
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from std_msgs.msg import Int32
from geometry_msgs.msg import PoseWithCovarianceStamped
from tf.broadcaster import TransformBroadcaster
from tf.transformations import quaternion_from_euler, euler_from_quaternion
from math import pi, sin, cos


class Pose:

    def __init__(self):
        self.x = 0
        self.y = 0
        self.theta = 0
        self.xVel = 0
        self.yVel = 0
        self.thetaVel = 0


    def __str__(self):
        return str({'x': self.x, 'y': self.y, 'theta': self.theta,
                    'xVel': self.xVel, 'yVel': self.yVel,
                    'thetaVel': self.thetaVel})


class Encoder:
    """Monitors a single wheel encoder and accumulates delta ticks
    since the last time they were requested.
    """

    def __init__(self):
        self.setRange(-32768, 32767)
        self.initCount(0)
        self.isReversed = False

    def setRange(self, low, high):
        self.range = high - low + 1
        self.lowThresh = low + self.range * 30 // 100
        self.highThresh = low + self.range * 70 // 100

    def initCount(self, startCount):
        self.delta = 0
        # self.last = startCount

    def update(self, increment):
        # if self.last > self.highThresh and newCount < self.lowThresh:
        #     # Wrapped around the upper limit
        #     increment = newCount + self.range - self.last
        # elif self.last < self.lowThresh and newCount > self.highThresh:
        #     # Wrapped around the lower limit
        #     increment = newCount - self.range - self.last
        # else:
        #     increment = newCount - self.last

        self.delta = increment
        # self.last += newCount

    def setReversed(self, isReversed):
        self.isReversed = isReversed

    def getDelta(self):
        delta = self.delta
        self.delta = 0
        if self.isReversed:
            return -delta
        else:
            return delta

    def getLimits(self):
        return {
            'range': self.range,
            'lowThresh': self.lowThresh,
            'highThresh': self.highThresh
        }

class Odometry_set:
    """Keeps track of the current position and velocity of a
    robot using differential drive.
    """

    def __init__(self):
        self.leftEncoder = Encoder()
        self.rightEncoder = Encoder()
        self.pose = Pose()
        self.lastTime = 0

    def setWheelSeparation(self, separation):
        self.wheelSeparation = separation

    def setTicksPerMeter(self, ticks):
        self.ticksPerMeter = ticks

    def setEncoderRange(self, low, high):
        self.leftEncoder.setRange(low, high)
        self.rightEncoder.setRange(low, high)

    def setTime(self, newTime):
        self.lastTime = newTime

    def updateLeftWheel(self, newCount):
        self.leftEncoder.update(newCount)

    def updateRightWheel(self, newCount):
        self.rightEncoder.update(newCount)

    def updatePose(self, newTime):
        """Updates the pose based on the accumulated encoder ticks
        of the two wheels. See https://chess.eecs.berkeley.edu/eecs149/documentation/differentialDrive.pdf
        for details.
        """
        leftTravel = self.leftEncoder.getDelta() / self.ticksPerMeter
        rightTravel = self.rightEncoder.getDelta() / self.ticksPerMeter
        deltaTime = newTime - self.lastTime

        deltaTravel = (rightTravel + leftTravel) / 2
        deltaTheta = (rightTravel - leftTravel) / self.wheelSeparation

        if rightTravel == leftTravel:
            deltaX = leftTravel * cos(self.pose.theta)
            deltaY = leftTravel * sin(self.pose.theta)
        else:
            radius = deltaTravel / deltaTheta

            # Find the instantaneous center of curvature (ICC).
            iccX = self.pose.x - radius * sin(self.pose.theta)
            iccY = self.pose.y + radius * cos(self.pose.theta)

            deltaX = cos(deltaTheta) * (self.pose.x - iccX) \
                     - sin(deltaTheta) * (self.pose.y - iccY) \
                     + iccX - self.pose.x

            deltaY = sin(deltaTheta) * (self.pose.x - iccX) \
                     + cos(deltaTheta) * (self.pose.y - iccY) \
                     + iccY - self.pose.y

        self.pose.x += deltaX
        self.pose.y += deltaY
        self.pose.theta = (self.pose.theta + deltaTheta) % (2 * pi)
        self.pose.xVel = deltaTravel / deltaTime if deltaTime > 0 else 0.
        self.pose.yVel = 0
        self.pose.thetaVel = deltaTheta / deltaTime if deltaTime > 0 else 0.

        self.lastTime = newTime

    def getPose(self):
        return self.pose

    def setPose(self, newPose):
        self.pose = newPose

class OdometryNode:

    def __init__(self):
        self.odometry = Odometry_set()

    def main(self):
        self.odomPub = rospy.Publisher('odom', Odometry, queue_size=10)
        self.tfPub = TransformBroadcaster()

        rospy.init_node('diff_drive_odometry')
        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        rospy.Subscriber("lwheel_ticks", Int32, self.leftCallback)
        rospy.Subscriber("rwheel_ticks", Int32, self.rightCallback)
        rospy.Subscriber("initialpose", PoseWithCovarianceStamped,
                         self.on_initial_pose)

        self.ticksPerMeter = int(rospy.get_param('~ticks_per_meter'))
        self.wheelSeparation = float(rospy.get_param('~wheel_separation'))
        self.rate = float(rospy.get_param('~rate', 10.0))
        self.baseFrameID = rospy.get_param('~base_frame_id', 'base_link')
        self.odomFrameID = rospy.get_param('~odom_frame_id', 'odom')
        self.encoderMin = int(rospy.get_param('~encoder_min', -32768))
        self.encoderMax = int(rospy.get_param('~encoder_max', 32767))

        self.odometry.setWheelSeparation(self.wheelSeparation)
        self.odometry.setTicksPerMeter(self.ticksPerMeter)
        self.odometry.setEncoderRange(self.encoderMin, self.encoderMax)
        self.odometry.setTime(rospy.get_time())

        rate = rospy.Rate(self.rate)
        while not rospy.is_shutdown():
            self.publish()
            rate.sleep()

    def publish(self):
        self.odometry.updatePose(rospy.get_time())
        now = rospy.get_rostime()
        pose = self.odometry.getPose()

        q = quaternion_from_euler(0, 0, pose.theta)
        self.tfPub.sendTransform(
            (pose.x, pose.y, 0),
            (q[0], q[1], q[2], q[3]),
            now,
            self.baseFrameID,
            self.odomFrameID
        )

        odom = Odometry()
        odom.header.stamp = now
        odom.header.frame_id = self.odomFrameID
        odom.child_frame_id = self.baseFrameID
        odom.pose.pose.position.x = pose.x
        odom.pose.pose.position.y = pose.y
        odom.pose.pose.orientation.x = q[0]
        odom.pose.pose.orientation.y = q[1]
        odom.pose.pose.orientation.z = q[2]
        odom.pose.pose.orientation.w = q[3]
        odom.twist.twist.linear.x = pose.xVel
        odom.twist.twist.angular.z = pose.thetaVel
        self.odomPub.publish(odom)

    def on_initial_pose(self, msg):
        q = [msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.x,
             msg.pose.pose.orientation.w]
        roll, pitch, yaw = euler_from_quaternion(q)

        pose = Pose()
        pose.x = msg.pose.pose.position.x
        pose.y = msg.pose.pose.position.y
        pose.theta = yaw

        rospy.loginfo('Setting initial pose to %s', pose)
        self.odometry.setPose(pose)

    def leftCallback(self, msg):
        self.odometry.updateLeftWheel(msg.data)

    def rightCallback(self, msg):
        self.odometry.updateRightWheel(msg.data)


if __name__ == '__main__':
    try:
        node = OdometryNode()
        node.main()
    except rospy.ROSInterruptException:
        pass
